import type { Metadata } from 'next'
import './globals.css'
import AuthProvider from "@/utils/authProvider";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import {getServerSession} from "next-auth";
import {authOptions} from "@/utils/authOptions";
import {redirect} from "next/navigation";
import {headers} from "next/headers";
import React from "react";
// import GoogleAnalytics from "@/app/GoogleAnalytics";
config.autoAddCss = false;

export const metadata: Metadata = {
    metadataBase: new URL("https://blueprintfactory.blog"),

  title: {
      default: "BlueprintFactory",
      template: `%s | BlueprintFactory`
  },
  description: 'Generated by create next app',
    category: 'business'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const headersList = headers();
    const pathname = headersList.get('x-pathname') || "";
    let data = null
    try {
        data = await getServerSession(authOptions);
    } catch (e) {
    }

    if (pathname.startsWith("/auth/admin") && (data == null || data.user.role !== "ADMIN")) {
        redirect("/home")
    }

    if (pathname.startsWith("/auth/user") && (data == null)) {
        redirect("/home")
    }

    return (
        <html lang="en">
            {/*<GoogleAnalytics />*/}
            <body>
                <AuthProvider>
                    <Header/>
                        {children}
                    <Footer/>
                </AuthProvider>
            </body>
        </html>
    )
}
