import type { Metadata } from 'next'
import './globals.css'
import AuthProvider from "@/utils/authProvider";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import {getServerSession} from "next-auth";
import {authOptions} from "@/app/api/auth/[...nextauth]/authOptions";
import {redirect} from "next/navigation";
import {headers} from "next/headers";
import React from "react";
import GoogleAnalytics from "@/utils/googleAnalytics";
import CookieBanner from "@/components/cookieBanner/cookieBanner";
import Head from "next/head";
import { Inter } from 'next/font/google'
// import GoogleAnalytics from "@/app/GoogleAnalytics";
config.autoAddCss = false;

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    metadataBase: new URL("https://blueprintfactory.blog"),

  title: {
      default: "BlueprintFactory",
      template: `%s | BlueprintFactory`
  },
  description: 'Generated by create next app',
    category: 'business',
    verification : {
        google: process.env.NEXT_PUBLIC_GOOGLE_ID
    }
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const gaMeasurementId = process.env.NEXT_PUBLIC_GOOGLE_ID || 'DEFAULT_MEASUREMENT_ID';

    return (
        <html lang="en" className={inter.className}>
            <GoogleAnalytics GA_MEASUREMENT_ID={gaMeasurementId}/>
            <body>
                <AuthProvider>
                    <Header/>
                        {children}
                    <Footer/>
                    <CookieBanner />
                </AuthProvider>
            </body>
        </html>
    )
}
